from farm_haystack.nodes.ranker.base import BaseRanker
from farm_haystack.nodes.ranker.sentence_transformers import SentenceTransformersRanker
from farm_haystack.nodes.ranker.cohere import CohereRanker
from farm_haystack.nodes.ranker.lost_in_the_middle import LostInTheMiddleRanker
from farm_haystack.nodes.ranker.diversity import DiversityRanker
from farm_haystack.nodes.ranker.recentness_ranker import RecentnessRanker
